### ISSUE TITLE
UnicodeDecodeError on 'exceptions.tsv' with Windows 10 Japanese Locale

### ISSUE THREAD

**Issue by 4890A** [polm/cutlet#10]
Windows attempts to decode exceptions.tsv with code point 932 instead of utf-8 for some reason. Setting the open keyword argument encoding=utf-8 fixes it.

`Traceback (most recent call last):
  File "cutlet_test.py", line 2, in <module>
    katsu = cutlet.Cutlet()
  File "C:\ProgramData\Miniconda3\envs\jpocr\lib\site-packages\cutlet\cutlet.py", line 80, in __init__
    self.exceptions = load_exceptions()
  File "C:\ProgramData\Miniconda3\envs\jpocr\lib\site-packages\cutlet\cutlet.py", line 59, in load_exceptions
    for line in open(cdir / 'exceptions.tsv'):
UnicodeDecodeError: 'cp932' codec can't decode byte 0x83 in position 10: illegal multibyte sequence`

**Comment by polm** [comment]
Thanks for the report and the quick fix!

**Comment by polm** [comment]
Just released v0.1.10, which should fix this.
