### ISSUE TITLE
KeyError being raised on certain characters

### ISSUE THREAD

**Issue by ykim** [polm/cutlet#7]
While experimenting with cutlet using the full unidic dictionary, I've had several KeyErrors being raised:

```
% cutlet
《月》
Traceback (most recent call last):
  File "/Users/ykim/.local/share/virtualenvs/sandbox-nIHPi2Hu/bin/cutlet", line 14, in <module>
    print(katsu.romaji(line.strip()))
  File "/Users/ykim/.local/share/virtualenvs/sandbox-nIHPi2Hu/lib/python3.8/site-packages/cutlet/cutlet.py", line 122, in romaji
    roma = self.romaji_word(word)
  File "/Users/ykim/.local/share/virtualenvs/sandbox-nIHPi2Hu/lib/python3.8/site-packages/cutlet/cutlet.py", line 175, in romaji_word
    return self.table[word.surface]
KeyError: '《'
% cutlet
くま　クマ　熊　ベアー　２【電子版特典付】
Traceback (most recent call last):
  File "/Users/ykim/.local/share/virtualenvs/sandbox-nIHPi2Hu/bin/cutlet", line 14, in <module>
    print(katsu.romaji(line.strip()))
  File "/Users/ykim/.local/share/virtualenvs/sandbox-nIHPi2Hu/lib/python3.8/site-packages/cutlet/cutlet.py", line 122, in romaji
    roma = self.romaji_word(word)
  File "/Users/ykim/.local/share/virtualenvs/sandbox-nIHPi2Hu/lib/python3.8/site-packages/cutlet/cutlet.py", line 192, in romaji_word
    return self.map_kana(kana)
  File "/Users/ykim/.local/share/virtualenvs/sandbox-nIHPi2Hu/lib/python3.8/site-packages/cutlet/cutlet.py", line 201, in map_kana
    out += self.get_single_mapping(pk, char, nk)
  File "/Users/ykim/.local/share/virtualenvs/sandbox-nIHPi2Hu/lib/python3.8/site-packages/cutlet/cutlet.py", line 234, in get_single_mapping
    return self.table[kk]
KeyError: '*'
```

Is this supposed to occur? I'm not aware if cutlet is meant to handle full-width characters in sentences.

**Comment by polm** [comment]
Thanks for the report, this is a bug. 

Let me look at fixing it...

**Comment by polm** [comment]
Pushed a fix for this, there were a couple of issues that your examples brought up:

- not handling punctuation like `《》【】`
- not handling zenkaku english/numbers

Those should be fixed in master now, I'll make a release with the fixes soon. Thanks for catching the bugs!
